import Head from "next/head"
import { Inter } from "@next/font/google"
import NavigationBar from "../components/NavigationBar/NavigationBar";
import Products from "../components/ProductsList/Products";
import Footer from "../components/Footer/Footer";
import {
  Box,
} from "@mui/material";


const inter = Inter({ subsets: ["latin"] })


export default function Home() {
  return(
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationBar />
        <Box
        >
          Hello
        </Box>
        <Products />
        <Footer />
      </main>
    </>
  )
}
